name: Deploy Ingress Nginx

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ingress-controller.yml

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: demo # Add your EKS cluster name here.

jobs:
  deploy_ingress_nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Configure kubectl to use the EKS cluster
    - name: Install and configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }}

    # Install the Ingress Nginx controller using Helm
    - name: Install and configure Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

    - name: Deploy ingress-nginx
      run: |
        helm upgrade --install --wait --cleanup-on-fail \
          --namespace ingress-nginx \
          --create-namespace \
          --set controller.admissionWebhooks.enabled=false \
          ingress-nginx ingress-nginx/ingress-nginx
