name: Build and Deploy to EKS

on:
  push:
    branches:
      - dev 
    paths:
    - tf-parser/terraform_parse_service/*
    - .github/workflows/tf-parser.yml
    - .github/manifests/tf-parser.yml

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: demo # Add your EKS cluster name here.
  DEPLOYMENT_NAME: tf-parser-app # Add your deployment name here.
  IMAGE: tf-parser

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Configure kubectl to use the EKS cluster
    - name: Install and configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build -f terraform_parse_service/Dockerfile \
          --tag "959377822120.dkr.ecr.us-east-1.amazonaws.com/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          terraform_parse_service/

    # Push the Docker image to Amazon Elastic Container Registry
    - name: Publish
      run: |-
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 959377822120.dkr.ecr.us-east-1.amazonaws.com
        docker push "959377822120.dkr.ecr.us-east-1.amazonaws.com/$IMAGE:$GITHUB_SHA"

    # Deploy the Docker image to the EKS cluster
    - name: Deploy
      run: |-
        sed -i -e 's|GITHUB_SHA|'"$GITHUB_SHA"'|' ${{ github.workspace }}/.github/manifests/tf-parser.yml
        sed -i -e 's|access-token|'"${{ secrets.ACCESS_TOKEN }}"'|' ${{ github.workspace }}/.github/manifests/tf-parser.yml
        kubectl apply -f ${{ github.workspace }}/.github/manifests/tf-parser.yml
